### ISSUE TITLE
Does Chinese data need additional change in the code?

### ISSUE THREAD

**Issue by drxmy** [amzn/trans-encoder#3]
Or will it  work just fine with Chinese? 
Really interesting work!

**Comment by hardyqr** [comment]
Thanks for your interest! 
In principle you shouldn't need to do much. You need to switch the English BERT models (incl. the initial bi-encoder and the base model) to Chinese ones. E.g., for bi-encoder you could use [simcse-chinese-roberta-wwm-ext](https://huggingface.co/cyclone/simcse-chinese-roberta-wwm-ext) (I randomly retrieved this one from google); and the corresponding base model is [hfl/chinese-roberta-wwm-ext](https://huggingface.co/hfl/chinese-roberta-wwm-ext).

**Comment by drxmy** [comment]
> 

Thank you for replying so quickly. Yes, the model definitely need to change. I was mainly concerned about data processing. I will try it tomorrow.

**Comment by zpp13** [comment]
@drxmy 请问你做过尝试了吗，效果怎么样

**Comment by drxmy** [comment]
> @drxmy 请问你做过尝试了吗，效果怎么样

我用的自己的数据集，现在的结果有一点奇怪，可能代码哪里没改对。bi-encoder每个cycle会验证两次，第一次指标很高，第二次就很低。不过最近一直没时间看是什么问题
![1](https://user-images.githubusercontent.com/39789137/148499952-3895db93-bcf7-4a76-8735-b0e4c5a27ea0.jpeg)
![2](https://user-images.githubusercontent.com/39789137/148499958-9a09345d-5a8b-48d9-90a7-72e60ad2806a.jpeg)
